# Generated by Django 3.1.6 on 2021-03-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_aduestiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('ne', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='uploads')),
            ],
        ),
    ]
