# Generated by Django 3.1.6 on 2021-03-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20210303_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='allnews',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
    ]
