# Generated by Django 3.1.6 on 2021-03-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_news_allnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='rating',
            field=models.CharField(blank=True, choices=[('b', 'Bad'), ('a', 'Average'), ('e', 'Excellent')], default='', max_length=1, null=True),
        ),
    ]
